<?

$attr_map = array(
    sg_skills_bonus_str => 'str_bonus',
    sg_skills_bonus_dex => 'dex_bonus',
    sg_skills_bonus_int => 'int_bonus',
    sg_skills_bonus_cha => 'cha_bonus',
    sg_skills_bonus_con => 'con_bonus',
    sg_skills_bonus_max_health => 'base_hp_bonus',
    sg_skills_fatigue_reduction => 'fatigue_reduction_bonus',
    sg_skills_gold_drop_boost => 'gold_bonus',
    sg_skills_bonus_melee_damage => 'melee_dmg_bonus',
    sg_skills_bonus_defend_damage => 'defend_dmg_bonus',
    sg_skills_bonus_xp_award_percent => 'xp_bonus',
    sg_skills_bonus_rep_award_percent => 'rep_bonus',
    sg_skills_bonus_fishing => 'fishing_bonus',
    sg_skills_bonus_mining => 'mining_bonus',
    sg_skills_item_drop_boost => 'item_bonus',
    sg_skills_bonus_buff_duration => 'buff_bonus',
    sg_skills_bonus_food_reduction => 'food_reduction',
    sg_skills_resist_fire => 'resist_' . sg_attacktype_fire,
    sg_skills_resist_water => 'resist_' . sg_attacktype_water,
    sg_skills_resist_earth => 'resist_' . sg_attacktype_earth,
    sg_skills_resist_air => 'resist_' . sg_attacktype_air,
    sg_skills_resist_arcane => 'resist_' . sg_attacktype_arcane,
    sg_skills_resist_electric => 'resist_' . sg_attacktype_electric,
    sg_skills_resist_necro => 'resist_' . sg_attacktype_necromancy,
    sg_skills_bonus_armour => 'armour',
    sg_skills_bonus_dodge => 'dodge_bonus',
    sg_skills_bonus_initiative => 'initiative_bonus',
    sg_skills_bonus_hunger => 'hunger_bonus',
    sg_skills_bonus_crafting_xp => 'crafting_xp_bonus',
    sg_skills_noncombat_freq_boost => 'noncombat_frequency_boost',
    sg_skills_bonus_crit => 'bonus_crit',
    sg_skills_bonus_to_hit => 'bonus_to_hit',
    sg_skills_bonus_mana_percent => 'bonus_mana_percent',
    sg_skills_bonus_armour_percent => 'bonus_armour_percent',
    sg_skills_bonus_health_percent => 'bonus_health_percent',
    sg_skills_mana_regen => 'mana_regen',
    sg_skills_bonus_melee_damage_percent => 'bonus_melee_dmg_percent',
    sg_skills_bonus_spell_damage => 'spell_dmg_bonus',
    sg_skills_hp_regen => 'hp_regen',
    sg_skills_rested_eating_bonus => 'rested_eating_bonus',
    sg_skills_resist_magical => 'resist_' . sg_attacktype_magical,
    sg_skills_xp_combat_bonus => 'xp_combat_bonus',
    sg_skills_pravokan => 'pravokan_bonus',
    sg_skills_fishing_fatigue_percent => 'fishing_fatigue',
    sg_skills_bonus_magic_dmg_percent => 'bonus_magic_dmg_percent',
    sg_skills_resist_physical => 'resist_' . sg_attacktype_physical,
    sg_skills_convert_magic_to_dmg_percent => 'convert_magic_dmg',
    sg_skills_reduce_cook_craft_fatigue_percent => 'reduce_craft_fatigue',
    sg_skills_dunnich => 'dunnich_bonus',
);

?>